name: gcmb-pipeline

dependencies:
  - python=3.13
  - conda-forge::pandas-gbq=0.27
  - conda-forge::pandas>=2.2.3, <2.3.0
  - conda-forge::geopandas=1
  - conda-forge::types-requests
  - conda-forge::autopep8
  - conda-forge::python-dotenv
  - conda-forge::tqdm=4
  - conda-forge::python-dotenv
  - conda-forge::libgdal-arrow-parquet
  - conda-forge::polars=1.31
  - conda-forge::geographiclib=2.0
  - conda-forge::dask=2025.7.0
  - conda-forge::dask-geopandas=0.5.0
